export const USER1 = 'test_user@test.com'
export const PASSWORD1 = 'abc123password'
export const USER2 = 'test_user2@test.com'
export const PASSWORD2 = 'abc123password'
export const TEST_URL = 'localhost:3000'
export const TEST_TEAM = 'test-team'
export const TEST_PROJECT = 'test-project'
export const TEST_PROJECT_EDITED = 'test-project-edited'
export const TEST_PROJECT_DESCRIPTION = 'test-project-description'
export const TEST_PROJECT_DESCRIPTION_EDITED = 'test-project-description-edited'
export const TEST_TASK = 'test-task-title'
export const TEST_TASK_DETAILS = 'test-task-details'

export const SIDEBAR_TASK = 'sidebar-menu-task-management'
export const SIDEBAR_DOCUMENTS = 'sidebar-menu-documents'
export const SIDEBAR_SUBMENU_TASKLIST = 'sidebar-submenu-task-list'
export const SIDEBAR_SUBMENU_KANBAN = 'sidebar-submenu-kanban-board'
export const SIDEBAR_SUBMENU_VIEW_CREATE_DOCS = 'sidebar-submenu-view/create-documents'
